/* 
 * API de Salas, Niveles, Dispositivos y Notificaciones
 *
 * Esta API permite gestionar las entidades:   - Salas: crear, borrar, modificar y consultar.   - Niveles: crear, borrar, modificar y consultar.   - Dispositivos: crear, borrar, modificar y consultar.   - Notificaciones: enviar notificaciones por email mediante los métodos:       • NotificarPresenciaSala       • NotificarUsuarioValido       • NotificarError 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NotificacionesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NotificacionesApiTests
    {
        private NotificacionesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NotificacionesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificacionesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NotificacionesApi
            //Assert.IsInstanceOfType(typeof(NotificacionesApi), instance, "instance is a NotificacionesApi");
        }

        /// <summary>
        /// Test NotificarError
        /// </summary>
        [Test]
        public void NotificarErrorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificacionesErrorBody body = null;
            //var response = instance.NotificarError(body);
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        /// <summary>
        /// Test NotificarPresenciaSala
        /// </summary>
        [Test]
        public void NotificarPresenciaSalaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NotificarPresenciaSala();
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        /// <summary>
        /// Test NotificarUsuarioValido
        /// </summary>
        [Test]
        public void NotificarUsuarioValidoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificacionesUsuarioValidoBody body = null;
            //var response = instance.NotificarUsuarioValido(body);
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
    }

}
