/* 
 * API de Salas, Niveles, Dispositivos y Notificaciones
 *
 * Esta API permite gestionar las entidades:   - Salas: crear, borrar, modificar y consultar.   - Niveles: crear, borrar, modificar y consultar.   - Dispositivos: crear, borrar, modificar y consultar.   - Notificaciones: enviar notificaciones por email mediante los métodos:       • NotificarPresenciaSala       • NotificarUsuarioValido       • NotificarError 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Nivel
    /// </summary>
    [DataContract]
        public partial class Nivel :  IEquatable<Nivel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Nivel" /> class.
        /// </summary>
        /// <param name="id">Identificador único (autogenerado).</param>
        /// <param name="nivel">Nivel (required).</param>
        /// <param name="descripcion">Descripción del nivel (required).</param>
        public Nivel(int? id = default(int?), int? nivel = default(int?), string descripcion = default(string))
        {
            // to ensure "nivel" is required (not null)
            if (nivel == null)
            {
                throw new InvalidDataException("nivel is a required property for Nivel and cannot be null");
            }
            else
            {
                this._Nivel = nivel;
            }
            // to ensure "descripcion" is required (not null)
            if (descripcion == null)
            {
                throw new InvalidDataException("descripcion is a required property for Nivel and cannot be null");
            }
            else
            {
                this.Descripcion = descripcion;
            }
            this.Id = id;
        }
        
        /// <summary>
        /// Identificador único (autogenerado)
        /// </summary>
        /// <value>Identificador único (autogenerado)</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Nivel
        /// </summary>
        /// <value>Nivel</value>
        [DataMember(Name="nivel", EmitDefaultValue=false)]
        public int? _Nivel { get; set; }

        /// <summary>
        /// Descripción del nivel
        /// </summary>
        /// <value>Descripción del nivel</value>
        [DataMember(Name="descripcion", EmitDefaultValue=false)]
        public string Descripcion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Nivel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Nivel: ").Append(_Nivel).Append("\n");
            sb.Append("  Descripcion: ").Append(Descripcion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Nivel);
        }

        /// <summary>
        /// Returns true if Nivel instances are equal
        /// </summary>
        /// <param name="input">Instance of Nivel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Nivel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this._Nivel == input._Nivel ||
                    (this._Nivel != null &&
                    this._Nivel.Equals(input._Nivel))
                ) && 
                (
                    this.Descripcion == input.Descripcion ||
                    (this.Descripcion != null &&
                    this.Descripcion.Equals(input.Descripcion))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this._Nivel != null)
                    hashCode = hashCode * 59 + this._Nivel.GetHashCode();
                if (this.Descripcion != null)
                    hashCode = hashCode * 59 + this.Descripcion.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
