/* 
 * API de Salas, Niveles, Dispositivos y Notificaciones
 *
 * Esta API permite gestionar las entidades:   - Salas: crear, borrar, modificar y consultar.   - Niveles: crear, borrar, modificar y consultar.   - Dispositivos: crear, borrar, modificar y consultar.   - Notificaciones: enviar notificaciones por email mediante los métodos:       • NotificarPresenciaSala       • NotificarUsuarioValido       • NotificarError 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Sala
    /// </summary>
    [DataContract]
        public partial class Sala :  IEquatable<Sala>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sala" /> class.
        /// </summary>
        /// <param name="id">Identificador único (autogenerado).</param>
        /// <param name="codigoSala">Código identificador de la sala (required).</param>
        /// <param name="nombre">Nombre de la sala (required).</param>
        /// <param name="nivel">Nivel al que pertenece la sala (required).</param>
        public Sala(int? id = default(int?), int? codigoSala = default(int?), string nombre = default(string), int? nivel = default(int?))
        {
            // to ensure "codigoSala" is required (not null)
            if (codigoSala == null)
            {
                throw new InvalidDataException("codigoSala is a required property for Sala and cannot be null");
            }
            else
            {
                this.CodigoSala = codigoSala;
            }
            // to ensure "nombre" is required (not null)
            if (nombre == null)
            {
                throw new InvalidDataException("nombre is a required property for Sala and cannot be null");
            }
            else
            {
                this.Nombre = nombre;
            }
            // to ensure "nivel" is required (not null)
            if (nivel == null)
            {
                throw new InvalidDataException("nivel is a required property for Sala and cannot be null");
            }
            else
            {
                this.Nivel = nivel;
            }
            this.Id = id;
        }
        
        /// <summary>
        /// Identificador único (autogenerado)
        /// </summary>
        /// <value>Identificador único (autogenerado)</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Código identificador de la sala
        /// </summary>
        /// <value>Código identificador de la sala</value>
        [DataMember(Name="codigoSala", EmitDefaultValue=false)]
        public int? CodigoSala { get; set; }

        /// <summary>
        /// Nombre de la sala
        /// </summary>
        /// <value>Nombre de la sala</value>
        [DataMember(Name="nombre", EmitDefaultValue=false)]
        public string Nombre { get; set; }

        /// <summary>
        /// Nivel al que pertenece la sala
        /// </summary>
        /// <value>Nivel al que pertenece la sala</value>
        [DataMember(Name="nivel", EmitDefaultValue=false)]
        public int? Nivel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Sala {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CodigoSala: ").Append(CodigoSala).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Nivel: ").Append(Nivel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Sala);
        }

        /// <summary>
        /// Returns true if Sala instances are equal
        /// </summary>
        /// <param name="input">Instance of Sala to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Sala input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.CodigoSala == input.CodigoSala ||
                    (this.CodigoSala != null &&
                    this.CodigoSala.Equals(input.CodigoSala))
                ) && 
                (
                    this.Nombre == input.Nombre ||
                    (this.Nombre != null &&
                    this.Nombre.Equals(input.Nombre))
                ) && 
                (
                    this.Nivel == input.Nivel ||
                    (this.Nivel != null &&
                    this.Nivel.Equals(input.Nivel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.CodigoSala != null)
                    hashCode = hashCode * 59 + this.CodigoSala.GetHashCode();
                if (this.Nombre != null)
                    hashCode = hashCode * 59 + this.Nombre.GetHashCode();
                if (this.Nivel != null)
                    hashCode = hashCode * 59 + this.Nivel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
