/* 
 * API de Salas, Niveles, Dispositivos y Notificaciones
 *
 * Esta API permite gestionar las entidades:   - Salas: crear, borrar, modificar y consultar.   - Niveles: crear, borrar, modificar y consultar.   - Dispositivos: crear, borrar, modificar y consultar.   - Notificaciones: enviar notificaciones por email mediante los métodos:       • NotificarPresenciaSala       • NotificarUsuarioValido       • NotificarError 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NotificacionesUsuarioValidoBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificacionesUsuarioValidoBodyTests
    {
        // TODO uncomment below to declare an instance variable for NotificacionesUsuarioValidoBody
        //private NotificacionesUsuarioValidoBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificacionesUsuarioValidoBody
            //instance = new NotificacionesUsuarioValidoBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificacionesUsuarioValidoBody
        /// </summary>
        [Test]
        public void NotificacionesUsuarioValidoBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificacionesUsuarioValidoBody
            //Assert.IsInstanceOfType<NotificacionesUsuarioValidoBody> (instance, "variable 'instance' is a NotificacionesUsuarioValidoBody");
        }


        /// <summary>
        /// Test the property 'Nif'
        /// </summary>
        [Test]
        public void NifTest()
        {
            // TODO unit test for the property 'Nif'
        }

    }

}
