/* 
 * API de Salas, Niveles, Dispositivos y Notificaciones
 *
 * Esta API permite gestionar las entidades:   - Salas: crear, borrar, modificar y consultar.   - Niveles: crear, borrar, modificar y consultar.   - Dispositivos: crear, borrar, modificar y consultar.   - Notificaciones: enviar notificaciones por email mediante los métodos:       • NotificarPresenciaSala       • NotificarUsuarioValido       • NotificarError 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Sala
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalaTests
    {
        // TODO uncomment below to declare an instance variable for Sala
        //private Sala instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Sala
            //instance = new Sala();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Sala
        /// </summary>
        [Test]
        public void SalaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Sala
            //Assert.IsInstanceOfType<Sala> (instance, "variable 'instance' is a Sala");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CodigoSala'
        /// </summary>
        [Test]
        public void CodigoSalaTest()
        {
            // TODO unit test for the property 'CodigoSala'
        }
        /// <summary>
        /// Test the property 'Nombre'
        /// </summary>
        [Test]
        public void NombreTest()
        {
            // TODO unit test for the property 'Nombre'
        }
        /// <summary>
        /// Test the property 'Nivel'
        /// </summary>
        [Test]
        public void NivelTest()
        {
            // TODO unit test for the property 'Nivel'
        }

    }

}
